#version 430
layout(local_size_x = 1, local_size_y = 1) in;

layout(std430, binding = 0) buffer lay0 {
    uint buf_one[];
};

layout(std430, binding = 1) buffer lay1 {
    float buf_two[];
};

layout(std430, binding = 2) buffer lay2 {
    int buf_three[];
};

void main() {
    const uint id = gl_GlobalInvocationID.x;

    buf_one[id] = buf_one[id] + buf_one[id];
    buf_two[id] = buf_two[id] * buf_two[id];
    buf_three[id] = int(id) - 4;
}
